#!/bin/bash
python ./gateway.py \
  --registry_id=my-registry \
  --gateway_id=my-gateway \
  --cloud_region=asia-east1 \
  --project_id=my-spark-test-iot \
  --private_key_file=gateway_rsa_private.pem \
  --algorithm=RS256 \
  --ca_certs=roots.pem \
  --mqtt_bridge_hostname=mqtt.googleapis.com \
  --mqtt_bridge_port=8883 \
  --jwt_expires_minutes=1200
